### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by KIsmoilov** [XRichardroidX/Course-R-Droid#2]
Please do the following changes to your web page:

- Please add the more button to the featured speaker's part
- Please make the flex-direction of boxes in a row in the main program section
- Please work on the contrast colors of the titles
- Please make the menu window fixed on mobile
- Please increase the height of the boxes in the main program section to make them responsive
- Please use the baseline for the flex items.
- Please focus on the margins and padding more.

**Comment by XRichardroidX** [comment]
Thanks for the Issues, they are all resolved now.
